// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://fmggbqrdbgfedjibdyhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtZ2dicXJkYmdmZWRqaWJkeWhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2MzMxNTksImV4cCI6MjA4ODIwOTE1OX0.PnIdXRBeA6U28uSLqa45q6BpWoqm8tdsxNIBc_2OAQc";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);